export const actionsTypes = {
  PITCH_IN: 'PITCH_IN',
  GET_ONE: 'GET_ONE',
  DELIVER_UPDATED_POT_TO_REDUCER: 'DELIVER_UPDATED_POT_TO_REDUCER',
  CURRENT_POT_TO_REDUCER: 'CURRENT_POT_TO_REDUCER',
  ASSIGNED_USERNAME: 'ASSIGNED_USERNAME',
  PUT_ALL_NAMES_TO_REDUCER: 'PUT_ALL_NAMES_TO_REDUCER',
  PICTHED_IN: 'PICTHED_IN',
  GOT_ONE: 'GOT_ONE',
  ANOTHER_ONE_PITCHED_IN: 'ANOTHER_ONE_PITCHED_IN'
};
